### ISSUE TITLE
[v6] Anonymous Issue

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#140] opened 2016-09-08 23:52 UTC
Submitter: Matthew
Email: volcarious@gmail.com
[v6]

This is my seed just in case you need it. C6832232. So in the palace of darkness I got to the point in the beginning where I need a key to continue, but I believe the key is behind a door that can only opened by defeating the Goriyas. and I need a bow to do that. unfortunately, I even looked at the spoiler log too, the bow is later in the dungeon, after the room I need the key for. Now i'm not sure about this, because I only came back to the dungeon after looking at the spoiler log and seeing the bow was in it, because I couldn't find it. but I think i had a key before that I used to get to the room with the Goriyas, either that or I'm remembering wrong and I never had a key at all.

**Comment by Tanean** [comment] 2016-09-09 00:50
I can confirm. The compass spawn in the shooter room, so you need to pass by the Goriya room since you don't have a key. The bow is later in the dungeon and you finish being stuck. The seed is unbeatable.
[dungeon-D1-B1] Dark Palace - shooter room................................................Compass
[dungeon-D1-1F] Dark Palace - maze room [bottom chest]....................................Bow

**Comment by BlueViper85** [comment] 2016-09-09 05:49
There are some known logic issues with Palace of Darkness.  The logic will be updated in the next version to avoid this situation as well as a few other soft-lock scenarios.  I am closing this issue as these changes are all being tracked as part of issue #123 

It is unfortunate that you've come across an unbeatable seed, but the majority of other seeds are beatable. I hope you continue to enjoy the randomizer.  Thanks for playing, and I wish you better luck with future seeds!

**Closed as completed by BlueViper85** 2016-09-09 05:49 UTC
