### ISSUE TITLE
[v7] Anonymous Issue

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#338] opened 2017-03-06 21:31 UTC
Submitter: Bert
[v7]
C4835415

Softlock in the sewer, no key spawning.

**Comment by BlueViper85** [comment] 2017-03-06 21:32
Duplicate of #337

**Closed as completed by BlueViper85** 2017-03-06 21:32 UTC

**Comment by BlueViper85** [comment] 2017-03-06 23:19
Correction: not a duplicate.

Sewers are part of Escape. Two blue guards have keys, a rat late in the sewers has a key and there is one in a chest. 

You'll need to backtrack (or restart) and validate that you killed each enemy and got their respective keys.

You may need to restart depending on how far you made it but fortunately it's not a lot of time lost.
