### ISSUE TITLE
[v7] The big Fairy from Lake Hylia give 99 Bombs and Arrows 

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#284] opened 2017-01-03 12:01 UTC
Submitter: Tantalus-X
Version: 7
Creation Date: 03.01.2017 01:51:04
Complexity: 6
Seed: C9075093

http://www.directupload.net/file/d/4589/bnsnyr9g_png.htm

have 50 bombs cap and 70 arrows cap found

the big give Fairy now 1 bombs and 1 arrow for 100 ruby

problenm is now she have not more give limit cane you set 99 ? and the numbers are not correct (is HEX code) which she says 

Ps:

the Mad Batter (Magic Meter 1/2 1/4) give nothing can you give random item ?

have you remove the 2 Fairy and the big Magic Potion in Link house ?

**Comment by ChristosOwen** [comment] 2017-01-03 17:48
The full magic and faerie in Link's House have been removed.

The "Mad Batter" can give you any random item.

You will get either 1/2 magic (2/3 chance) or 1/4 magic (1/3 chance) in every seed. It is randomly placed and part of the regular item pool.

The great faerie upgrades by 1 per 100 rupees for each of bombs and arrows because there are instant max capacity upgrades for 50 bombs and 70 arrows in the item pool now. So this prevents (or at least makes it a pain) to upgrade your bombs/arrows past 50/70, i.e. the intended maximum.

In v8 the bomb/arrow upgrades will be split over six +5 and one +10 upgrade instead of instant 50/70, as to mimic the great faerie more closely. Then in v9 the upgrade faerie fountains will be changed also. It's intended you don't use the great faerie fountain in randomizer as she doesn't yet serve much of a function but she will from v9.

However there are no issues here, everything is working as intended, and no immediate action required, so I am going to close this one.

Thanks for playing and hope you continue to have fun! Let me know if you have any further quesitons :)

**Closed as completed by ChristosOwen** 2017-01-03 17:48 UTC
