### ISSUE TITLE
[v6] Bug in Dark Palace

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#204] opened 2016-11-18 07:55 UTC
Submitter: Stephen
[v6]
In regard to seed "C7291165"

In the dark room right before the big chest, the room is completely black (I haven't found the Lantern yet). I'll try to grope my way through the darkness to find the small chest and bombable wall, but I thought you guys would like to know.

On a separate note, great work with this randomizer. It's a breath of fresh air in arguable my favorite game of all time :)

**Comment by BlueViper85** [comment] 2016-11-18 08:19
No email provided. Posting response here in hopes this might be seen and closing the issue.

Thanks for the feedback, glad you're enjoying randomizer!

This is by design. The lamp is required to light up dark rooms in the Dark World. The lamp will not be placed in a location that would require you to navigate a dark room in order to get it.

A part of randomizer is doing the dungeons out of order, which can be required in situations where you can't plrogresss without it. 

That being said, if you can manage your way through a dark room without the lamp everything will still function as intended. Chests still open (though contents may not appear through the dark) and all enemies, doors and obstacles work the same.

Good luck and let us know if you find anymore issues!

**Closed as completed by BlueViper85** 2016-11-18 08:19 UTC
