### ISSUE TITLE
C2466640

### ISSUE THREAD

**Issue by Lulzigi** [Dessyreqt/alttprandomizer#235] opened 2016-12-18 23:54 UTC
Please correct me if I am wrong, but I think I've found an unbeatable seed (without glitches of course). There's a couple of problems I'm having, but the main one at the moment is that the bow is in the Dark Palace beyond a locked door and the only accessible chest has the power glove and the others require either a key or the bow to defeat a red Goriya. Am I missing something and the bow isn't required, or is this just unbeatable?

Sorry if this isn't the right place for this. I couldn't find any place else to put it. 

Gah! Now that I found the "Report an Issue" button I've double posted this issue and it won't let me delete either one! Sorry!

**Comment by BlueViper85** [comment] 2016-12-19 00:32
Thanks for the feedback!  The report issue button submits the issue here so either works; however, creating it here with your own account helps ensure you get notified of updates. I closed the other issue as a duplicate of this one.

With that out of the way, this issue is a known issue with the logic of Palace of Darkness in v6. This has been addressed in v7 for when it releases (there is no ETA at this time).

If you have any other issues or questions, please let us know! I'll close this issue for now, but you can still comment if necessary.

**Closed as completed by BlueViper85** 2016-12-19 00:32 UTC
