### ISSUE TITLE
Seed C5976851 - Flippers in the Zora Heart Piece location

### ISSUE THREAD

**Issue by BlueViper85** [Dessyreqt/alttprandomizer#43] opened 2016-07-28 06:33 UTC
Seed# C5976851

Per the spoiler log:

Piece of Heart (Zora's River).............................................................Flippers

Seed is unbeatable without major glitches

**Comment by Dessyreqt** [comment] 2016-07-28 08:11
Closing as duplicate of #33

**Closed as completed by Dessyreqt** 2016-07-28 08:11 UTC
