### ISSUE TITLE
[v6] Fairy Fountain Heal issue

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#107] opened 2016-08-23 02:09 UTC
Submitter: Neil White
Email: Morendo@gmail.com
[v6]

Encountered a glitch that causes all Pendants in the Inventory to be removed when healing at a Fairy Fountain. This occurs while healing in both Light and Dark worlds.
- The player can re-obtain any pendant by entering the boss room of the appropriate dungeon. The boss will already be defeated, and the pendant will spawn as if the boss had just been defeated.

Seeds encountered:
C6046616
C1982999

**Comment by KatDevsGames** [comment] 2016-08-23 02:46
Duplicate of #8. Already fixed in trunk rom.

**Closed as completed** 2016-08-23 02:46 UTC
