### ISSUE TITLE
[v5] Impossible to Proceed C5914927

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#75] opened 2016-08-06 23:11 UTC
Submitter: Andrew S
Email: ashutt92@yahoo.com
Currently finished the Eastern Palace, however after reading through the spoiler log, the Book of Mudora and the Magic Mirror are in the Dark World, while the Hammer is in an inaccessible area of the Light World. Without two of the three, I cannot proceed to any other dungeon, nor another portal to the rest of the Dark World.

**Comment by KatDevsGames** [comment] 2016-08-07 02:22
Nothing is preventing player from getting hookshot at the sanctuary, 
going to kakriko well and getting the cape, heading directly for agahnim 
1, and grabbing the mirror right from the side of the pyramid. Player 
can then hookshot by the broken bridge and grab mitts from skull woods.

Seed is doable. Not a bug / won't fix.

**Closed as completed** 2016-08-07 02:22 UTC
