### ISSUE TITLE
[v6] Anonymous Issue

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#236] opened 2016-12-19 00:05 UTC
Submitter: Lulzigi
[v6]

Please correct me if I am wrong, but I think I've found an unbeatable seed (without glitches of course). There's a couple of problems I'm having, but the main one at the moment is that the bow is in the Dark Palace beyond a locked door and the only accessible chest has the power glove and the others require either a key or the bow to defeat a red Goriya. Am I missing something and the bow isn't required, or is this just unbeatable?

Right after I posted this as an issue, I found the "Report an Issue" button when opening the randomizer. Sorry about that. The seed is C2466640.

**Comment by BlueViper85** [comment] 2016-12-19 00:25
Duplicate of #235

**Closed as completed by BlueViper85** 2016-12-19 00:25 UTC
