### ISSUE TITLE
#FALSE ALERT seed required speedrun strategy to complete

### ISSUE THREAD

**Issue by TheRealYasri** [Dessyreqt/alttprandomizer#105] opened 2016-08-22 07:41 UTC
Cant not beat the second or third dungeons in the light world because of lack of fire starter items, And because I can see no way to access the titan's mitts I can not get into the dark world for them. There might be a speed running glitch I do not know about but as just a standard player this seed looks unwinnable.

**Comment by TheRealYasri** [comment] 2016-08-22 07:42
## A Link to the Past Randomizer Log

Version: 6
Creation Date: 8/20/2016 10:32:14 PM
Seed: C6141985

## Generated Item Order

[dungeon-C-B1] Escape - first B1 room.....................................................Pegasus Boots
[cave-016] cave under rocks west of Santuary..............................................Cape
[cave-050] cave southwest of Lake Hylia [bottom left chest]...............................Book of Mudora
[cave-021] Kakariko well [bottom chest]...................................................Shovel
Bottle Vendor.............................................................................Flippers
[dungeon-L2-B1] Desert Palace - Map room..................................................Power Glove
[cave-021] Kakariko well [right chest row of 3]...........................................Magic Mirror
[cave-047] Dam............................................................................Hookshot
[cave-009-1F] Death Mountain - wall of caves - right cave [bottom chest]..................Bow
Piece of Heart (Pyramid)..................................................................Lamp
[dungeon-C-B1] Escape - final basement room [left chest]..................................Bottle (Fairy)
Piece of Heart (Lumberjack Tree)..........................................................Titan's Mitt
Ether.....................................................................................Mushroom
[cave-009-B1] Death Mountain - wall of caves - right cave [left chest]....................Moon Pearl
Piece of Heart (Digging Game).............................................................Hammer
Piece of Heart (Dark World - bumper cave).................................................Bombos
[cave-056] Dark World Death Mountain - cave under boulder [bottom left chest].............Fire Rod
[cave-009-B1] Death Mountain - wall of caves - right cave [right chest]...................Ocarina
[cave-073] cave northeast of swamp palace [bottom chest]..................................Quake
[cave-073] cave northeast of swamp palace - generous guy..................................Cane of Somaria
Flute Boy.................................................................................Ice Rod

## Light World

[cave-009-1F] Death Mountain - wall of caves - right cave [bottom chest]..................Bow
[cave-009-1F] Death Mountain - wall of caves - right cave [top left chest]................300 Rupees
[cave-009-1F] Death Mountain - wall of caves - right cave [top left middle chest].........Bottle (Blue Potion)
[cave-009-1F] Death Mountain - wall of caves - right cave [top right chest]...............20 Rupees
[cave-009-1F] Death Mountain - wall of caves - right cave [top right middle chest]........Piece of Heart
[cave-009-B1] Death Mountain - wall of caves - right cave [left chest]....................Moon Pearl
[cave-009-B1] Death Mountain - wall of caves - right cave [right chest]...................Ocarina
[cave-012-1F] Death Mountain - wall of caves - left cave..................................Piece of Heart
[cave-013] Mimic cave (from Turtle Rock)..................................................20 Rupees
[cave-016] cave under rocks west of Santuary..............................................Cape
[cave-018] Graveyard - top right grave....................................................3 Bombs
[cave-021] Kakariko well [bottom chest]...................................................Shovel
[cave-021] Kakariko well [center chest row of 3]..........................................Bottle
[cave-021] Kakariko well [left chest row of 3]............................................Piece of Heart
[cave-021] Kakariko well [right chest row of 3]...........................................Magic Mirror
[cave-021] Kakariko well [top chest]......................................................3 Bombs
[cave-022-B1] Thief's hut [bottom left chest].............................................Piece of Heart
[cave-022-B1] Thief's hut [bottom right chest]............................................100 Rupees
[cave-022-B1] Thief's hut [top chest].....................................................Piece of Heart
[cave-022-B1] Thief's hut [top left chest]................................................50 Rupees
[cave-022-B1] Thief's hut [top right chest]...............................................Heart Container
[cave-026] chicken house..................................................................20 Rupees
[cave-031] Tavern.........................................................................10 Arrows
[cave-034] Hyrule Castle secret entrance..................................................Blue Mail
[cave-035] Sahasrahla's Hut [center chest]................................................20 Rupees
[cave-035] Sahasrahla's Hut [left chest]..................................................50 Rupees
[cave-035] Sahasrahla's Hut [right chest].................................................10 Arrows
[cave-040] Link's House...................................................................3 Bombs
[cave-044] Aginah's cave..................................................................3 Bombs
[cave-047] Dam............................................................................Hookshot
[cave-050] cave southwest of Lake Hylia - generous guy....................................3 Bombs
[cave-050] cave southwest of Lake Hylia [bottom left chest]...............................Book of Mudora
[cave-050] cave southwest of Lake Hylia [bottom right chest]..............................20 Rupees
[cave-050] cave southwest of Lake Hylia [top left chest]..................................20 Rupees
[cave-050] cave southwest of Lake Hylia [top right chest].................................20 Rupees
[cave-051] Ice Cave.......................................................................Piece of Heart
Bombos....................................................................................10 Arrows
Bottle Vendor.............................................................................Flippers
Ether.....................................................................................Mushroom
Haunted Grove item........................................................................1 Rupee
Hobo......................................................................................Piece of Heart
King Zora.................................................................................3 Bombs
Library...................................................................................20 Rupees
Mushroom..................................................................................20 Rupees
Old mountain man..........................................................................3 Bombs
Piece of Heart (Dam)......................................................................3 Bombs
Piece of Heart (Death Mountain - floating island).........................................Ether
Piece of Heart (Desert - northeast corner)................................................Piece of Heart
Piece of Heart (Desert - west side).......................................................10 Arrows
Piece of Heart (Graveyard)................................................................300 Rupees
Piece of Heart (Lake Hylia)...............................................................100 Rupees
Piece of Heart (Lumberjack Tree)..........................................................Titan's Mitt
Piece of Heart (Maze Race)................................................................3 Bombs
Piece of Heart (south of Haunted Grove)...................................................5 Rupees
Piece of Heart (Spectacle Rock Cave)......................................................Piece of Heart
Piece of Heart (Spectacle Rock)...........................................................Piece of Heart
Piece of Heart (Thieves' Forest Hideout)..................................................Piece of Heart
Piece of Heart (Zora's River).............................................................50 Rupees
Purple Chest..............................................................................3 Bombs
Sahasrahla................................................................................Piece of Heart
Sick Kid..................................................................................10 Arrows
Witch.....................................................................................Piece of Heart

## Dark World

[cave-055] Spike cave.....................................................................20 Rupees
[cave-056] Dark World Death Mountain - cave under boulder [bottom left chest].............Fire Rod
[cave-056] Dark World Death Mountain - cave under boulder [bottom right chest]............10 Arrows
[cave-056] Dark World Death Mountain - cave under boulder [top left chest]................Piece of Heart
[cave-056] Dark World Death Mountain - cave under boulder [top right chest]...............10 Arrows
[cave-057-1F] Dark World Death Mountain - cave from top to bottom [bottom chest]..........Piece of Heart
[cave-057-1F] Dark World Death Mountain - cave from top to bottom [top chest].............20 Rupees
[cave-062] C-shaped house.................................................................50 Rupees
[cave-063] doorless hut...................................................................20 Rupees
[cave-071] Misery Mire west area [left chest].............................................1 Rupee
[cave-071] Misery Mire west area [right chest]............................................100 Rupees
[cave-073] cave northeast of swamp palace - generous guy..................................Cane of Somaria
[cave-073] cave northeast of swamp palace [bottom chest]..................................Quake
[cave-073] cave northeast of swamp palace [bottom middle chest]...........................Piece of Heart
[cave-073] cave northeast of swamp palace [top chest].....................................3 Bombs
[cave-073] cave northeast of swamp palace [top middle chest]..............................20 Rupees
Catfish...................................................................................300 Rupees
Flute Boy.................................................................................Ice Rod
Piece of Heart (Dark World - bumper cave).................................................Bombos
Piece of Heart (Dark World blacksmith pegs)...............................................3 Bombs
Piece of Heart (Digging Game).............................................................Hammer
Piece of Heart (Pyramid)..................................................................Lamp
Piece of Heart (Treasure Chest Game)......................................................3 Bombs

## Hyrule Castle Escape

[dungeon-C-1F] Sanctuary..................................................................Staff of Byrna
[dungeon-C-B1] Escape - final basement room [left chest]..................................Bottle (Fairy)
[dungeon-C-B1] Escape - final basement room [middle chest]................................20 Rupees
[dungeon-C-B1] Escape - final basement room [right chest].................................20 Rupees
[dungeon-C-B1] Escape - first B1 room.....................................................Pegasus Boots
[dungeon-C-B1] Hyrule Castle - boomerang room.............................................Map
[dungeon-C-B1] Hyrule Castle - map room...................................................Key
[dungeon-C-B3] Hyrule Castle - next to Zelda..............................................Piece of Heart

## Eastern Palace

[dungeon-L1-1F] Eastern Palace - big ball room............................................Map
[dungeon-L1-1F] Eastern Palace - big chest................................................Compass
[dungeon-L1-1F] Eastern Palace - Big key..................................................100 Rupees
[dungeon-L1-1F] Eastern Palace - compass room.............................................20 Rupees
[dungeon-L1-1F] Eastern Palace - map room.................................................Big Key

## Desert Palace

[dungeon-L2-B1] Desert Palace - big chest.................................................Map
[dungeon-L2-B1] Desert Palace - Big key room..............................................Compass
[dungeon-L2-B1] Desert Palace - compass room..............................................Big Key
[dungeon-L2-B1] Desert Palace - Map room..................................................Power Glove

## Tower of Hera

[dungeon-L3-1F] Tower of Hera - first floor...............................................Big Key
[dungeon-L3-2F] Tower of Hera - Entrance..................................................20 Rupees
[dungeon-L3-4F] Tower of Hera - 4F [small chest]..........................................Compass
[dungeon-L3-4F] Tower of Hera - big chest.................................................Map

## Hyrule Castle Tower

[dungeon-A1-2F] Hyrule Castle Tower - 2 knife guys room...................................Key
[dungeon-A1-3F] Hyrule Castle Tower - maze room...........................................Key

## Dark Palace

[dungeon-D1-1F] Dark Palace - big chest...................................................20 Rupees
[dungeon-D1-1F] Dark Palace - big key room................................................Piece of Heart
[dungeon-D1-1F] Dark Palace - compass room................................................Key
[dungeon-D1-1F] Dark Palace - jump room [left chest]......................................Key
[dungeon-D1-1F] Dark Palace - jump room [right chest].....................................Key
[dungeon-D1-1F] Dark Palace - maze room [bottom chest]....................................Key
[dungeon-D1-1F] Dark Palace - maze room [top chest].......................................50 Rupees
[dungeon-D1-1F] Dark Palace - spike statue room...........................................Map
[dungeon-D1-1F] Dark Palace - statue push room............................................Compass
[dungeon-D1-B1] Dark Palace - room leading to Helmasaur [left chest]......................Big Key
[dungeon-D1-B1] Dark Palace - room leading to Helmasaur [right chest].....................100 Rupees
[dungeon-D1-B1] Dark Palace - shooter room................................................Key
[dungeon-D1-B1] Dark Palace - turtle stalfos room.........................................Key

## Swamp Palace

[dungeon-D2-1F] Swamp Palace - first room.................................................Key
[dungeon-D2-B1] Swamp Palace - big chest..................................................Map
[dungeon-D2-B1] Swamp Palace - big key room...............................................Piece of Heart
[dungeon-D2-B1] Swamp Palace - map room...................................................Piece of Heart
[dungeon-D2-B1] Swamp Palace - push 4 blocks room.........................................Big Key
[dungeon-D2-B1] Swamp Palace - south of hookshot room.....................................10 Arrows
[dungeon-D2-B2] Swamp Palace - flooded room [left chest]..................................10 Arrows
[dungeon-D2-B2] Swamp Palace - flooded room [right chest].................................Compass
[dungeon-D2-B2] Swamp Palace - hidden waterfall door room.................................Red Boomerang

## Skull Woods

[dungeon-D3-B1] Skull Woods - big chest...................................................50 Rupees
[dungeon-D3-B1] Skull Woods - Big Key room................................................Compass
[dungeon-D3-B1] Skull Woods - Compass room................................................Big Key
[dungeon-D3-B1] Skull Woods - east of Fire Rod room.......................................Key
[dungeon-D3-B1] Skull Woods - Entrance to part 2..........................................Map
[dungeon-D3-B1] Skull Woods - Gibdo/Stalfos room..........................................Key
[dungeon-D3-B1] Skull Woods - south of Fire Rod room......................................Key

## Thieves Town

[dungeon-D4-1F] Thieves' Town - Room above boss...........................................Map
[dungeon-D4-B1] Thieves' Town - Bottom left of huge room [bottom right chest].............Key
[dungeon-D4-B1] Thieves' Town - Bottom left of huge room [top left chest].................20 Rupees
[dungeon-D4-B1] Thieves' Town - Bottom right of huge room.................................20 Rupees
[dungeon-D4-B1] Thieves' Town - Top left of huge room.....................................Big Key
[dungeon-D4-B2] Thieves' Town - big chest.................................................Compass
[dungeon-D4-B2] Thieves' Town - next to Blind.............................................100 Rupees

## Ice Palace

[dungeon-D5-B1] Ice Palace - Big Key room.................................................Key
[dungeon-D5-B1] Ice Palace - compass room.................................................Bug-Catching Net
[dungeon-D5-B2] Ice Palace - map room.....................................................Map
[dungeon-D5-B3] Ice Palace - spike room...................................................20 Rupees
[dungeon-D5-B4] Ice Palace - above Blue Mail room.........................................Big Key
[dungeon-D5-B5] Ice Palace - b5 up staircase..............................................Key
[dungeon-D5-B5] Ice Palace - big chest....................................................Compass

## Misery Mire

[dungeon-D6-B1] Misery Mire - big chest...................................................Compass
[dungeon-D6-B1] Misery Mire - big hub room................................................Key
[dungeon-D6-B1] Misery Mire - big key.....................................................300 Rupees
[dungeon-D6-B1] Misery Mire - compass.....................................................Key
[dungeon-D6-B1] Misery Mire - end of bridge...............................................Key
[dungeon-D6-B1] Misery Mire - map room....................................................Map
[dungeon-D6-B1] Misery Mire - spike room..................................................Big Key

## Turtle Rock

[dungeon-D7-1F] Turtle Rock - Chain chomp room............................................Key
[dungeon-D7-1F] Turtle Rock - compass room................................................Key
[dungeon-D7-1F] Turtle Rock - Map room [left chest].......................................Compass
[dungeon-D7-1F] Turtle Rock - Map room [right chest]......................................Big Key
[dungeon-D7-B1] Turtle Rock - big chest...................................................50 Rupees
[dungeon-D7-B1] Turtle Rock - big key room................................................Key
[dungeon-D7-B1] Turtle Rock - Roller switch room..........................................Map
[dungeon-D7-B2] Turtle Rock - Eye bridge room [bottom left chest].........................Bottle (Green Potion)
[dungeon-D7-B2] Turtle Rock - Eye bridge room [bottom right chest]........................Key
[dungeon-D7-B2] Turtle Rock - Eye bridge room [top left chest]............................20 Rupees
[dungeon-D7-B2] Turtle Rock - Eye bridge room [top right chest]...........................20 Rupees

## Ganon's Tower

[dungeon-A2-1F] Ganon's Tower - above Armos...............................................3 Bombs
[dungeon-A2-1F] Ganon's Tower - big chest.................................................20 Rupees
[dungeon-A2-1F] Ganon's Tower - compass room [bottom left chest]..........................20 Rupees
[dungeon-A2-1F] Ganon's Tower - compass room [bottom right chest].........................Key
[dungeon-A2-1F] Ganon's Tower - compass room [top left chest].............................5 Rupees
[dungeon-A2-1F] Ganon's Tower - compass room [top right chest]............................Key
[dungeon-A2-1F] Ganon's Tower - down right staircase from entrance [left chest]...........3 Bombs
[dungeon-A2-1F] Ganon's Tower - down right staircase from entrance [right chest]..........Piece of Heart
[dungeon-A2-1F] Ganon's Tower - east of down right staircase from entrace.................Key
[dungeon-A2-1F] Ganon's Tower - map room..................................................Magic Powder
[dungeon-A2-1F] Ganon's Tower - north of gap room [bottom left chest].....................Piece of Heart
[dungeon-A2-1F] Ganon's Tower - north of gap room [bottom right chest]....................Red Shield
[dungeon-A2-1F] Ganon's Tower - north of gap room [top left chest]........................20 Rupees
[dungeon-A2-1F] Ganon's Tower - north of gap room [top right chest].......................1 Arrow
[dungeon-A2-1F] Ganon's Tower - north of teleport room....................................Red Mail
[dungeon-A2-1F] Ganon's Tower - west of teleport room [bottom left chest].................3 Bombs
[dungeon-A2-1F] Ganon's Tower - west of teleport room [bottom right chest]................Big Key
[dungeon-A2-1F] Ganon's Tower - west of teleport room [top left chest]....................Compass
[dungeon-A2-1F] Ganon's Tower - west of teleport room [top right chest]...................10 Arrows
[dungeon-A2-6F] Ganon's Tower - before Moldorm............................................Map
[dungeon-A2-6F] Ganon's Tower - Moldorm room..............................................Piece of Heart
[dungeon-A2-6F] Ganon's Tower - north of falling floor four torches [top left chest]......3 Bombs
[dungeon-A2-6F] Ganon's Tower - north of falling floor four torches [top right chest].....10 Arrows
[dungeon-A2-B1] Ganon's Tower - north of Armos room [bottom chest]........................Boomerang
[dungeon-A2-B1] Ganon's Tower - north of Armos room [left chest]..........................Piece of Heart
[dungeon-A2-B1] Ganon's Tower - north of Armos room [right chest].........................Mirror Shield

## Special Locations

Magic Bat.................................................................................1/4 Magic
Misery Mire Required Medallion............................................................Quake
Pyramid Bottle Item.......................................................................Bottle (Bee)
Turtle Rock Required Medallion............................................................Quake
Waterfall Bottle Item.....................................................................Bottle (Bee)

**Comment by JingerTV** [comment] 2016-08-22 07:49
It's possible with the Magic Cape to bypass the energybarrier for agahnim, so when you got the Moon Pearl you can access early to the Darkworld.

**Comment by TheRealYasri** [comment] 2016-08-22 08:16
Yep it worked just did it, got to dark world with the lamp right next to the port in and then went to get the mitts, from under the cut tree in the light world.

**Comment by gbirchmeier** [comment] 2016-08-22 15:52
You should close this issue then.

**Comment by KatDevsGames** [comment] 2016-08-22 15:53
Not a bug.

**Closed as completed by KatDevsGames** 2016-08-22 15:53 UTC
