### ISSUE TITLE
[v6] Impossible seed C3548150?

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#168] opened 2016-09-23 07:37 UTC
Submitter: Pamfafoofle
Email: david_ford@sil.org
Version: 6
Creation Date: 9/22/2016 5:06:24 PM
Seed: C3548150

I’d like to report what I believe is an impossible seed…maybe you can see if there’s something I missed. This is my second playthrough of the randomizer; my first I beat with every item, every upgrade and all 20 Heart Containers, and I’m therefore pretty confident I know the location of all possible chests/item locations. I’m an expert at the original LttP and OCD about 100% completion.

The spoiler log for this seed indicates that the Moon Pearl is stuck on the Dark World Pyramid (which, now that I think about it, is a really unique location, since it’s the only Dark World item location in the game that Bunny Link could access as best I can think.) I can enter the Dark World from several teleporters with Hammer and Power Glove, but can’t do anything useful there without the Moon Pearl, and since saving in the Dark World pre-Moon Pearl returns me to the Light World instead of placing me atop the Pyramid, the only way to proceed in the quest would be to fight Agahnim. Since I don’t have the Cape (locked in the Dark World), the only alternative I’m aware of to enter Agahnim’s Tower is to get all 3 Pendants/Master Sword. However, without either the Lamp or Fire Rod (both of which are locked in the Dark World), I am unable to proceed to the boss of either Desert Palace or Tower of Hera.

Items I do have are Bow, Red Boomerang, Hookshot, Bombs, Hammer, Shovel, Book of Mudora, Bottle x3, Magic Mirror, Power Glove, Blue Mail, Sword L1, Shield L1.

Is this an impossible seed, or have I missed something? If the former, I hope this information will be helpful to you in a future update. If the latter, hopefully the information will be helpful to me in future plays.

~Pamfafoofle

**Comment by BlueViper85** [comment] 2016-09-23 16:46
This seed is in-fact unbeatable. This is essentially a duplicate of Issue #125, where this fix will be tracked.

**Closed as completed by BlueViper85** 2016-09-23 16:46 UTC

**Comment by BlueViper85** [comment] 2016-09-23 17:14
Sent the following directly to Pamfafofle via e-mail so he is aware of the status of this seed and that this is marked for resolution via issue 125.
