### ISSUE TITLE
Magic Bat missing from Spoiler Log and add whether 1/2 or 1/4 magic was generated to spoiler log

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#290] opened 2017-01-05 17:36 UTC
Submitter: Anonymous 
[v7]
Previously the spoiler log used to have the datum of if the rom generated gave 1/2 magic or 1/4 magic when the cave-033 side-quest was completed in a consistently location at one end of the spoiler log or the other.  That information is still present but that information's location in the spoiler log has been randomized.
***** Request: place the information whether the seed generates 1/2 magic or 1/4 magic in a consistent location.

The spoiler log, as far as I can see does not include any information as to what is contained in cave-033 the blacksmiths' well magic altar cave.
The spoiler log, as far as I can tell, does not include any information as to what is contained in cave-049 the wishing well.

But I do not know what if anything those two places are called in the current spoiler log generation programming.  But I suspect that cave-033 and cave-049 are not listed at all by the spoiler log programming in the current update.
***** Request: list cave-033 in the spoiler log
***** Request: list cave-049 in the spoiler log

not a real feature request:
I would just like to see a spoiler log for the non-randomized version of the game including Complexity Analysis.  Since the spoiler log for all players for all non-randomized versions of the game should be the same I feel that generating a spoiler log for the non-randomized version of the rom should not be included as a feature.  Instead I am requesting this log just be generated once (per Alttprandomizer version) by Dessyreqt or mmxbass or Karkat or whomever and then posted somewhere for all to read.

Future updates request:
Easy mode: Similar to casual mode but always generates 1/4 magic and Ganon's Tower contains no items, thus Ganon's Tower's randomized chests are limited to Ganon's Tower's dungeon items and 1 rupee, 5 rupees, 20 rupees, 1 arrow, 10 arrows, and 3 bombs chests.
Projared mode: Big chests always contain 10 arrows. 
Note that these two modes are not mutually exclusive.
C- normal casual
J- Projared casual, P for Jared because he's not a Pro he's a causal Jared.
G- normal glitched
P- Projared glitched, P for Projared because he's got to be a pro to pull this off.
E- Normal Easy, E for easy
A- Projared Easy, A for arrows.

**Comment by BlueViper85** [comment] 2017-01-05 18:26
Of this entire submission, I see one significantly actionable item, and one reasonable request.  Marking as both a Bug and a Feature Request because of each of these:

> ***** Request: place the information whether the seed generates 1/2 magic or 1/4 magic in a consistent location.

Marked as a Feature Request because this seems like a reasonable request for the "Special Locations" section of the spoiler log.  But it is also easily searched for via CTRL+F in whatever text editor the spoiler log opens in.

> ***** Request: list cave-033 in the spoiler log

Marked as a bug because I confirmed that this location is, in-fact, missing from the spoiler logs.  I checked for both Cave  033 and for Magic Bat and saw neither on the list.

As for the rest:

> ***** Request: list cave-049 in the spoiler log

This is the Fountain of Wishes in Lake Hylia which does not currently give an item, so no change seems necessary until this is added to the locations pool.

> not a real feature request:
> I would just like to see a spoiler log for the non-randomized version of the game including Complexity Analysis. Since the spoiler log for all players for all non-randomized versions of the game should be the same I feel that generating a spoiler log for the non-randomized version of the rom should not be included as a feature. Instead I am requesting this log just be generated once (per Alttprandomizer version) by Dessyreqt or mmxbass or Karkat or whomever and then posted somewhere for all to read.

The complexity levels are calculated by the ability to access new locations once the necessary item(s) is/are obtained.  The complexity analysis would really be about a 6-8:

1. Lamp from Escape gives you the ability to light torches, Eastern Palace gives you the Bow, which gives you the Pendant of Courage (Green), giving access to Sahasrala who gives you the boots, which gives you access to the Book of Mudora and Desert Palace
2. Power Gloves from Desert Palace gives you access to the flippers, mirror, and the Tower of Hera and the Pendant of Power (Blue)
3. Moon Pearl from Tower of Hera gives you access to the roam the Dark World safely and gives you access to the Pendant of Wisdom (Red)
4. All three pendants give you the Master Sword which gives you access to Ether and Agahnim's tower which, when coupled with the Moon Pearl gives you access to the Palace of Darkness
5. Palace of Darkness gives you access to the Hammer which (with the mirror) gives you access to the entire light world and most of the dark world)
6. The hammer (when coupled with the mirror) gives you access to Thieve's Town and Titan's Mitts which gives you access to every dungeon and item you need to beat the game.  (This one might actually be multiple steps, since FireRod in Skull Woods 1 (or bombos after getting the hammer) gives access to Ice Palace, and the Cane of Somaria in Misery Mire gives access to Turtle Rock)

> Easy mode: Similar to casual mode but always generates 1/4 magic and Ganon's Tower contains no items, thus Ganon's Tower's randomized chests are limited to Ganon's Tower's dungeon items and 1 rupee, 5 rupees, 20 rupees, 1 arrow, 10 arrows, and 3 bombs chests.

I can see the appeal of Easy mode, but I don't think it really fits with the goals of the Randomizer.

>Projared mode: Big chests always contain 10 arrows.

A good joke for those who saw his play through, but clearly serves no actual purpose

**Comment by BlueViper85** [comment] 2017-01-05 19:40
It seems that the Bat will show up in the complexity analysis if he has something progressive, but still doesn't show up in the general list of locations.

The Magic Bat location is missing the region, adding `Region = Region.LightWorld,` to this location addes it to the spoiler log.

**Comment by BlueViper85** [comment] 2017-01-29 18:33
The fix for this issue has been applied to the base code and will be available when the next version is released (no ETA).  Closing this issue since a fix has been applied.

**Closed as completed by BlueViper85** 2017-01-29 18:33 UTC
Labels: bug, Feature Request
