### ISSUE TITLE
Flute (Ocarina) Dissapeared. version 6 SD2SNES

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#98] opened 2016-08-20 04:36 UTC
Submitter: David Thomas
Email: ginistrepupu@gmail.com
[v6]

Ok so I got the Flute aka Ocarina early from a chest. Later on during the game after talking to the flute kid I found a shovel in a chest. When I got the shovel the game took the flute away. It just disappeared from my inventory. I don't know why. I was also playing the game on my SD2SNES flash cart on a real super nintendo. It just sucked that the flute disappeared because you need it to get in misery mire. Anyway I just wanted to let you all know.

**Comment by KatDevsGames** [comment] 2016-08-20 04:43
You should be able to Y-toggle the item. Please attach your SRM file so I can investigate.

On August 20, 2016 12:36:32 AM EDT, David Carroll notifications@github.com wrote:

> Submitter: David Thomas
> Email: ginistrepupu@gmail.com
> [v6]
> 
> Ok so I got the Flute aka Ocarina early from a chest. Later on during
> the game after talking to the flute kid I found a shovel in a chest.
> When I got the shovel the game took the flute away. It just disappeared
> from my inventory. I don't know why. I was also playing the game on my
> SD2SNES flash cart on a real super nintendo. It just sucked that the
> flute disappeared because you need it to get in misery mire. Anyway I
> just wanted to let you all know.
> 
> ## 
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Dessyreqt/alttprandomizer/issues/98

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ChristosOwen** [comment] 2016-08-24 11:43
Either way this is a duplicate of #89 so closing this one. 99% sure this is not being aware you can toggle the menu.

**Closed as completed by ChristosOwen** 2016-08-24 11:43 UTC
