### ISSUE TITLE
[v6] Lamp fix run not Dark Palace

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#177] opened 2016-10-02 21:10 UTC
Submitter: Tantalus-X
Email: Tantalus-X@hotmail.de
 Lamp fix run not in the Dark Palace is  now  i bug or not ?

 have not lamp

**Comment by BlueViper85** [comment] 2016-10-02 21:29
Sent the following e-mail to Tantalus regarding this.  Closing this as it is either not an issue or there was insufficient info to determine what bug may exist.  If more info is provided and a bug is identified, this issue can be re-opened or a new one created.

Hello, Tantalus-X,

Regarding your issue about the lamp:

In the Light World and its dungeons, the dark rooms are lit whether you have the lamp or not.  In the dark world and it's dungeons the lamp is required to see in those rooms.  The lamp will never be in a location where you need the lamp to get it.  This is fully intentional and is not a bug.  

You'll need to leave Dark Palace and return once you find the lamp OR try to navigate the rooms without the lamp (which is NOT recommended).

If you believe the lamp is somewhere that you need it to obtain, please let us know the seed you're using and we can look further.

Thanks for the feedback!  Please post any comments or questions you may have to the GitHub page for your issue (https://github.com/Dessyreqt/alttprandomizer/issues/177) or you can respond to this e-mail.

Hope you continue to enjoy randomizer!  Let us know if you run across any other concerns or problems.

BlueViper85

[Edit: The GitHub page shortens the full link to this issue to just the number, but the full link was provided in the e-mail]

**Closed as completed by BlueViper85** 2016-10-02 21:29 UTC
Labels: question
