### ISSUE TITLE
Is there a way to get my seed number? (Stuck)

### ISSUE THREAD

**Issue by Xyrexus** [Dessyreqt/alttprandomizer#137] opened 2016-09-07 16:39 UTC
I'm having trouble finding the Fire Rod on my sister's file and it's getting kinda annoying looking everywhere for it, but I'm silly and renamed her file so I wouldn't get it confused with mine... would it be possible to get my file's seed number somehow? I'll include it here.

[New WinRAR ZIP archive.zip](https://github.com/Dessyreqt/alttprandomizer/files/459729/New.WinRAR.ZIP.archive.zip)

**Comment by BlueViper85** [comment] 2016-09-08 00:28
Based on the file name of the SFC file as well as the seed number identified, this appears to be a duplicate of #138 

For safety's sake, the seed number is C3406875.

Sorry for the delay in providing this.  Please let us know if you run into any other issues!

**Closed as completed by BlueViper85** 2016-09-08 00:28 UTC

**Comment by Niamek** [comment] 2016-09-08 15:00
It would be neat if you could make it display on the title screen or something, like SMW randomizer or Dragon Warrior 1 randomizer. Not required though.

**Comment by KatDevsGames** [comment] 2016-09-08 16:30
Niamek, please see #138.

**Comment by Niamek** [comment] 2016-09-09 17:02
Yes I saw that. I just say that this could be an enhancement as I said it's not required.

**Comment by KatDevsGames** [comment] 2016-09-09 17:09
It should be possible without much trouble... perhaps for people like sd2snes users I suppose we should do this.

**Comment by SmashManiac** [comment] 2016-09-09 22:19
One potential disadvantage I can think of showing the seed within the game would be streamers having the solution spoiled by their chat. Not sure if that would be that much of a problem though.

**Comment by BlueViper85** [comment] 2016-09-10 01:27
i think if it's limited to a short screen, say the "-NINTENDO- screen, or the title/name entry screen that wouldn't be much of an issue. Keep it away from consistent viewership by chat/comments (for the youtubers) wouldn't be bad.

But either way I think in terms of priority this would be a low request. It's available when the emulator loads, and in the file name and spoiler log as it is today.

**Comment by Niamek** [comment] 2016-09-10 02:43
Exactly. Dragon Warrior 1 Randomizer and Super Mario World randomizer put them on the title screen.

It would help a lot for guys who uses emlators that doesn't even display the text you pointed out in the other issue... Or for guys that disabled them(if we can disable them)
