### ISSUE TITLE
[v6] Seed C0272727 Unbeatable

### ISSUE THREAD

**Issue by Eppy37** [Dessyreqt/alttprandomizer#125] opened 2016-08-31 07:14 UTC
My friend TeamUDF came across this seed which appears to be unbeatable. The main issue is that the Moon Pearl spawns on the Pyramid. 

The Magic Cape spawns in Misery Mire area preventing early access into Hyrule Castle Tower.

The Fire Rod and lamp also spawn in the Palace of Darkness and Cave NE of Swamp Palace, respectively, making Desert Palace unbeatable and obtaining the Master Sword the normal way. 

While Titan's Mitt and Hammer are obtainable in the light world, all of the portals that have access to the pyramid area have some form of obstruction right at the portal exit like a hammer peg that can't be passed as a Bunny.

I can't think of any other solution for this one.

**Comment by BlueViper85** [comment] 2016-08-31 21:13
Reviewed spoiler log and can confirm that this seed is not beatable without glitches.

From what I've seen of the logic, it looks as though it might be a problem with the logic surrounding one of the conditions for accessing the Pyramid.  Mitts and Flippers are accessible, but without the moon pearl the flippers and mitts aren't usable to access the Pyramid.  But I may be reading the logic incorrectly.

**Comment by ChristosOwen** [comment] 2016-08-31 22:23
For KarKat:

If it's NOT following you, then mirror, s+q and changing screens removes it. Not sure which of these are like this in vanilla, so may need to change 1, 2 or all 3 of them!

If it IS following you, then no changes are needed -- mirror, s+q and changing screens keeps it, as per vanilla.

**Comment by ChristosOwen** [comment] 2016-08-31 22:25
Indeed this is unbeatable, and the issue is indeed with the Pyramid function. It's already been flagged and will be fixed in the next version. Sorry for the error! Closing as it's a duplicate :)

**Comment by ChristosOwen** [comment] 2016-08-31 22:30
Actually leaving open to serve as a reminder for Dessy!

**Comment by ChristosOwen** [comment] 2016-11-04 02:34
This had been addressed and will be working correctly in v7.

**Closed as completed by ChristosOwen** 2016-11-04 02:34 UTC
Labels: bug
