### ISSUE TITLE
Mysterious Pond Fairy is glitched

### ISSUE THREAD

**Issue by churine** [Dessyreqt/alttprandomizer#62] opened 2016-08-05 01:21 UTC
I suspect it may be related to the extra inventory, as I had done little else

I got shovel, mushroom, and magic powder
I also had titan's mitt, power glove, and L3 Sword (and moon pearl)
with that kind of inventory, some odd items are available to be thrown, in my case **an unchecked pendant**

throwing the unchecked pendant makes her "give you" -92 rupees
after that, the unchecked pendant wasn't available to be thrown, but **an extra L3 sword option appeared**, before what I suspect is the real one (which does nothing special)

throwing this one gave me the L4 sword, as the Pyramid Fairy
after that, everything was normal

--- update: **it's throwing the shovel or magic powder what cause extra, glitch options to appear**; powder gives big key, which counts as a bee. Likely mushroom and ocarina will give glitched options as well.

Seed: C7314108

**Comment by KatDevsGames** [comment] 2016-08-05 03:38
Duplicate of #51 .

**Closed as completed by KatDevsGames** 2016-08-05 03:38 UTC
