### ISSUE TITLE
[v5] Infinite Digging

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#60] opened 2016-08-04 10:57 UTC
Submitter: ChristosOwen
Email: ChristosOwen@hotmail.co.uk
[v5] If you dig on a corner of a slope you can dig infinitely and spawn items infinitely. Works on the lower tile of the slanted wall just to the right of Ganon's Tower. twitch.tv/wildanaconda69 - his last broadcast has it in (right near the end before he cuts his stream) - no idea if it works elsewhere but would imagine so?

**Comment by KatDevsGames** [comment] 2016-08-05 03:38
Confirmed. Looking into more detail tomorrow after recovering geiger savestates.

**Comment by BlueViper85** [comment] 2016-08-07 17:43
I did happen to find that this also happens elsewhere.  For example at this corner just before/after the Digging Game screen.

![2016-08-07 2](https://cloud.githubusercontent.com/assets/12190332/17464118/60070a30-5c9c-11e6-8bfe-0e8941abe392.png)

**Comment by KatDevsGames** [comment] 2016-08-11 17:50
This may not make it into v6 since we're running low on time and it's not actually breaking at all.

**Comment by ChristosOwen** [comment] 2016-09-04 19:34
We should probably fix this because if you get shovel in Link's house then you can really quickly farm bombs (for secret room chests in Escape) using corners on the way to Hyrule Castle. This gives people who know about this trick an unfair advantage over those who don't and dig a new spot every time.

It's minor but still something that should be addressed at some point if possible probably.

**Comment by KatDevsGames** [comment] 2016-09-16 07:55
Going to try and get this into v7.

**Comment by KatDevsGames** [comment] 2016-10-13 01:30
Fixed in trunk for v7.

**Closed as completed by KatDevsGames** 2016-10-13 01:30 UTC
Labels: bug
