### ISSUE TITLE
V7 Test Seed C9887501 - Turtle Rock Unbeatable

### ISSUE THREAD

**Issue by BlueViper85** [Dessyreqt/alttprandomizer#256] opened 2016-12-27 03:41 UTC
Submitted via Discord by modustrollens1985:

C9887501 TRock has no key in Compass room or Map room.  I can't progress

I confirmed via spoiler log. The first three chests were Ice Rod, Big Key, and 300 Rupeees

**Comment by Dessyreqt** [comment] 2016-12-27 06:54
Closing as duplicate of #245

**Closed as completed by Dessyreqt** 2016-12-27 06:54 UTC
