### ISSUE TITLE
Flute disappearing from inventory

### ISSUE THREAD

**Issue by allencpalmer** [Dessyreqt/alttprandomizer#89] opened 2016-08-14 05:55 UTC
Happened on two separate seeds, one time I had used it and then it was gone the next time I tried to use it, another time before I even had a chance to free the bird with it.  Locked out of Misery Mire as a result.

**Comment by KatDevsGames** [comment] 2016-08-14 06:42
We'll need to know which seeds, what you were doing at the time, etc.

On August 14, 2016 1:55:25 AM EDT, allencpalmer notifications@github.com wrote:

> Happened on two separate seeds, one time I had used it and then it was
> gone the next time I tried to use it, another time before I even had a
> chance to free the bird with it.  Locked out of Misery Mire as a
> result.  
> 
> ## 
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Dessyreqt/alttprandomizer/issues/89

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by allencpalmer** [comment] 2016-08-14 07:04
I don't have the seed for the first time, the second time was seed C8336341
Got the flute from the tavern in the village.  Released the bird, and flew
to the point south of Lake Hylia.  Got the item in the ice rod spot, then
left that cave and tried to fly away.  The flute was missing.  The HUD does
not show it in my inventory either.

**Comment by allencpalmer** [comment] 2016-08-14 07:07
I did find the first seed that it happened on actually, C2990970

**Comment by allencpalmer** [comment] 2016-08-14 08:44
I was able to mirror glitch through the wall into Misery Mire to complete
the play through. Thanks so much for breathing life into this old game. I
look forward to seeing what you guys are up to in the future.

**Comment by KatDevsGames** [comment] 2016-08-22 00:04
Can you attach a screenshot of your hud with the cursor over the flute/shovel cell, if possible?

**Comment by ChristosOwen** [comment] 2016-08-24 11:35
Surely this is a case of the player didn't read the notes and realise you can toggle between Shovel and Flute?

**Comment by ChristosOwen** [comment] 2016-08-26 22:03
Either that or it's a duplicate of #93 so closing either way.

**Closed as completed by ChristosOwen** 2016-08-26 22:03 UTC
