### ISSUE TITLE
Shovel permanently gone

### ISSUE THREAD

**Issue by churine** [Dessyreqt/alttprandomizer#67] opened 2016-08-05 06:15 UTC
After obtaining the Ocarina, the Shovel was removed as normal, even though the update says otherwise
(I did already obtain the item that was in the Ocarina location)
this is the same playthrough as the glitched waterfall fairy, in where I tossed the shovel and glitch items resulting from it
other similar items (boomerang, powder, bottles) worked fine

**Comment by KatDevsGames** [comment] 2016-08-05 06:48
This is clearly all the same bug and almost certainly a clash at 7ef358

Likely fix is to move *358 to later address. Fairy is clearly corrupting / clearing it mistakenly not realizing it's not an item slot. Will verify later when actually at a computer.

On August 5, 2016 2:15:22 AM EDT, zilarch notifications@github.com wrote:

> After obtaining the Ocarina, the Shovel was removed as normal, even
> though the update says otherwise
> (I did already obtain the item that was in the Ocarina location)
> this is the same playthrough as the glitched waterfall fairy, in where
> I tossed the shovel and glitch items resulting from it
> other similar items (boomerang, powder, bottles) worked fine
> 
> ---
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Dessyreqt/alttprandomizer/issues/67

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by KatDevsGames** [comment] 2016-08-05 17:07
Throwing shovel corrupted it. This is a duplicate of #51.

**Closed as completed** 2016-08-05 17:07 UTC
