### ISSUE TITLE
v4 seed C3388559 - Flippers unreachable

### ISSUE THREAD

**Issue by crusso109** [Dessyreqt/alttprandomizer#35] opened 2016-07-10 21:59 UTC
http://i.imgur.com/nhncExt.png
## Generated Item Order

[cave-022-B1] Thief's hut [top chest].....................................................Bow
[dungeon-L1-1F] Eastern Palace - compass room.............................................Bottle
[cave-021] Kakariko well [left chest row of 3]............................................Pegasus Boots
[cave-021] Kakariko well [center chest row of 3]..........................................Book of Mudora
[dungeon-L2-B1] Desert Palace - compass room..............................................Cape
[cave-022-B1] Thief's hut [top left chest]................................................Power Glove
Piece of Heart (Zora's River).............................................................Flippers
[cave-050] cave southwest of Lake Hylia [bottom left chest]...............................Hookshot
Piece of Heart (Lumberjack Tree)..........................................................Magic Mirror
[cave-047] Dam............................................................................Fire Rod
King Zora.................................................................................Moon Pearl
[dungeon-D2-B2] Swamp Palace - flooded room [left chest]..................................Titan's Mitt
Piece of Heart (Desert - west side).......................................................Lamp / 5 rupees
Purple Chest..............................................................................Shovel
[cave-062] C-shaped house.................................................................Hammer
[cave-009-1F] Death Mountain - wall of caves - right cave [top right middle chest]........Ether
[cave-009-1F] Death Mountain - wall of caves - right cave [top right chest]...............Quake
[dungeon-D4-B2] Thieves' Town - next to Blind.............................................Cane of Somaria
[cave-073] cave northeast of swamp palace [top chest].....................................Mirror Shield
[dungeon-D4-B2] Thieves' Town - big chest.................................................Ice Rod

**Comment by Dessyreqt** [comment] 2016-07-15 23:28
Closing as duplicate of #33

**Closed as completed by Dessyreqt** 2016-07-15 23:28 UTC
