### ISSUE TITLE
Flute shovel issue.

### ISSUE THREAD

**Issue by GonthorianDX** [Dessyreqt/alttprandomizer#99] opened 2016-08-20 05:08 UTC
been playing through a wonderful seed and got the flute pretty early (15 second race) but much later on i find the shovel in the chest and now it has overridden my flute and i still need it to finish the misery mire and ice palace.

did i do something wrong or is it a problem with the coding?
would love to see these two items untouched if they override each other.
here is the seed i am playing on: C8398879

flute at 15 second race, shovel in chest in death mountain light world.

**Comment by KatDevsGames** [comment] 2016-08-20 05:25
The items should be available for Y-toggle as explained in the release notes. If that is not the case, please submit your SRM file.

On August 20, 2016 1:08:00 AM EDT, GonthorianDX notifications@github.com wrote:

> been playing through a wonderful seed and got the flute pretty early
> (15 second race) but much later on i find the shovel in the chest and
> now it has overridden my flute and i still need it to finish the misery
> mire and ice palace.
> 
> did i do something wrong or is it a problem with the coding?
> would love to see these two items untouched if they override each
> other.
> 
> ## 
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Dessyreqt/alttprandomizer/issues/99

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by GonthorianDX** [comment] 2016-08-20 05:35
aha, did not realise i could switch those two items. it seems to be working correctly for me.
thanks a lot, i will continue my adventures now.

**Comment by KatDevsGames** [comment] 2016-08-21 23:55
Closed as not a bug.

**Closed as completed by KatDevsGames** 2016-08-21 23:55 UTC
