### ISSUE TITLE
broken seed

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#143] opened 2016-09-10 14:29 UTC
Submitter: Cronofighter
Email: paraptor@web.de
the bow in this seed in the dark palace behind a key door. but to get a key you must kill a red rat that can only be killed with bow

**Comment by ChristosOwen** [comment] 2016-09-10 15:25
Duplicate of #144

**Closed as completed by ChristosOwen** 2016-09-10 15:25 UTC
