### ISSUE TITLE
Disappearing Pendant

### ISSUE THREAD

**Issue by Michpem** [Dessyreqt/alttprandomizer#61] opened 2016-08-04 18:04 UTC
This isn't that much of an issue since you can get it again, but in my seed (C1564941), I was able to get the Red Pendant early, but when I got either the second Crystal or the Blue Pendant (I'm not sure which one triggered the glitch because I just noticed it), it simply disappeared from my inventory. The map marked it again in the Tower of Hera, so I went there and, to my surprise, it reappeared in the boss room despite me getting it earlier in the game.

Edit: Now I talked to the sick kid in Kakariko and the Blue and Red Pendants disappeared again.

**Comment by churine** [comment] 2016-08-05 05:31
getting the pendant of courage also removed the same pendant for me

**Comment by KatDevsGames** [comment] 2016-08-05 17:14
I'm trying to sort this into two piles. It seems every inventory bug is caused by one of two things.

So... did you visit any great fairy fountains for item upgrades?

**Comment by churine** [comment] 2016-08-06 01:29
a different playthrough I did not visit a fairy fountain still removed the red and green pendants upon collecting the blue, without affecting the intended functionality of the Y items (unless you are supposed to be able to switch between normal and silver arrows later on, too?)

but it's inconsistent- quickly testing on the same seed (with debug, i.e. I didn't collect _anything else_) the blue pendant didn't remove anything after collecting it last
crystals all seem unaffected

(I did visit the pyramid fountain at the end of the game, which worked completely normal)

Glitch items to throw into the waterfall also seem to appear upon collecting pendants

**Comment by KatDevsGames** [comment] 2016-08-06 03:00
Not sure if fixed but might be. Sending WIP trunk to dess for testing.

**Comment by ChristosOwen** [comment] 2016-08-06 10:29
As a side note - could be interesting to add the toggle feature to Bow and Silver Arrows?

**Comment by churine** [comment] 2016-08-13 23:50
Not fixed, both this and fairy fountain remain broken.

It does have some interesting behavior with Zarby89's HUD, athough I'm unsure if these are simply unrelated issues on the program or indicates some sort of memory conflict, but I figure details might help pin things down.

First of all, these are _just in the display_: the Shield was not registered there as obtained along the Sword at the start of the game, and later on upgrading it instead glitched the Ocarina's spot.
However, it was getting the shield when the blue pendant disappeared this time.
Also interestingly, the in-game display showed the pendant grayed out, but the HUD showed it fine, even though both were synced correctly before.

Collecting the green pendant removed the red pendant still, even though all three remained on the HUD.
They were really gone in-game though, so I suppose that detail might be on the program's fault.

Also in the program, the _missing_ pendants (i.e. not courage) and unregistered shield can be manually marked and removed, unlike everything else that updates with the game. (Including the supposed glitched ocarina)

**Comment by KatDevsGames** [comment] 2016-08-14 01:18
Provide exact reproduction steps to any fairy fountain problem you believe you may have found. Extra inventory is no longer even in the effective range of the fairy fountain which, lacking other logic changes besides a 1-byte item change for bottles, is effectively vanilla fairy fountain.

**Comment by KatDevsGames** [comment] 2016-08-18 16:37
Finally figured this out. Corruption is caused by big (not great) fairies. Fixed in trunk rom.

**Closed as completed by KatDevsGames** 2016-08-18 16:37 UTC
