### ISSUE TITLE
SRAM Trace bug

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#167] opened 2016-09-22 11:26 UTC
Submitter: Tantalus-X
Email: Tantalus-X@hotmail.de
[v6]

the SRAM Trace make unlock switch option for all item the have 2 option Mushroom instantly to Magic Powder and Shovel to Flute + bird unlock instantly

me test Seed: C8302360

ps have you contact to Zarbry89 the hud rund not good and is bugy the hud add not Shields and the Flute item is Blue Mail in the Hud oO

**Comment by BlueViper85** [comment] 2016-09-22 15:39
This SRAM Trace option has been found to cause early access to these items in both the ZSNES and SNESGT emulators. This issue is known and being tracked in issue #93.  I'm closing this as it is a duplicate of that.

As for the issue with the HUD, that can be reported to Zarby directly at his HUD Page: https://github.com/Zarby89/ZeldaHud/issues

I've gone ahead and opened this as an issue for you there, but should you find any more bugs with the HUD those are best reported on that site instead of here.

**Closed as completed by BlueViper85** 2016-09-22 15:39 UTC
