### ISSUE TITLE
Moon pearl in the tower of hera. Soft lock

### ISSUE THREAD

**Issue by MrPatafoin** [Dessyreqt/alttprandomizer#182] opened 2016-10-12 22:10 UTC
If this item is in the 4F big or small chest , AND if the big key is in the room where we need need a lamp or a fire rod. The game can be impossible if we can't have the lamp or the fire rod before the moon pearl.

I got 2 seeds (played at the same night, lol) where it's impossible to beat the game : 
- C9918281, 
  [dungeon-L3-1F] Tower of Hera - first floor...............................................Big Key
  [dungeon-L3-4F] Tower of Hera - 4F [small chest]..........................................Moon Pearl
  [dungeon-D2-B1] Swamp Palace - big key room...............................................Fire Rod
  Purple Chest..............................................................................Lamp

-C6749878,
[dungeon-L3-1F] Tower of Hera - first floor...............................................Big Key
[dungeon-L3-4F] Tower of Hera - 4F [small chest]..........................................Moon Pearl
Piece of Heart (south of Haunted Grove)...................................................Lamp
[cave-055] Spike cave.....................................................................Fire Rod

**Comment by BlueViper85** [comment] 2016-10-13 03:15
Generated spoiler logs to confirm placement of items in these situations, and I can confirm that these appear unbeatable.

I **think** that this may relate to issue #125 based on my understanding of the current logic.  I'll leave this open for ChristosOwen to review and confirm.  If so, this can be closed as it will be fixed as part of that issue. Otherwise this should be treated separately.

**Comment by ChristosOwen** [comment] 2016-10-13 15:19
I've investigated this issue in depth. For both seeds all the logic for all item locations seems correct. 

For the first seed:

The logic currently (correctly) requires Moon Pearl to enter Dark Palace, which contain Titan's Mitts, which makes obtaining the Lamp impossible. The logic also (correctly) requires Moon Pearl to access South Dark World (in cases where you reach Pyramid Area without Moon Pearl). Swamp Palace (correctly) requires CanAccessSouthDarkWorld to enter, which ensures Moon Pearl is required. This makes obtaining Fire Rod impossible. The faulty logic with Pyramid and Moon Pearl appears not to be the cause.

For the second seed:

The Spike Cave specifically has Moon Pearl in the logic. The Piece of Heart (south of Haunted Grove) has CanAccessSouthDarkWorld, which ensures Moon Pearl is required. Again, the faulty Pyramid logic appears not to be the cause.

Conclusion:

There must be an issue elsewhere; likely places are the CanAccessSouthDarkWorld function or Tower of Hera item locations. I checked the former and it seems fine, but it could use a second pair of eyes. As for Hera:

The _"[dungeon-L3-4F] Tower of Hera - 4F [small chest]"_ logic (correctly) requires Big Key to reach, although it does appear to be missing "&& CanLightTorches(have)" which it should have had, however this doesn't change anything for this issue report since the chest containing the Big Key does have this requirement for both seeds. 

I don't understand how this distribution was possible with the logic that is in place. I'm stumped. I need help with this one.

As a separate point, Tower of Hera is due an overhaul with the (!LocationHasItem("[dungeon-L3-1F] Tower of Hera - first floor", ItemType.BigKey) function anyway for v7.

**Comment by KatDevsGames** [comment] 2016-10-13 16:31
The problem here appears to be that it's only using BigKeyNeeded to know where to not put the big key. What it actually needs to do is for each chest that has BigKeyNeeded=true, find the big key in that dungeon and add all the requirements for the chest containing the big key to all chests that have BigKeyNeeded=true.

Pasted from IRC:
the Location class needs a settable property that takes a lambda expression
if it's null, defaults to n=>true
if it's not, it gets evaluated
and is added as a conditional to the CanAccess expression
that way you can just look up the big key chest
put that chest's CanAccess as the lambda in all chests that have BigKeyNeeded = true

**Comment by ChristosOwen** [comment] 2016-10-16 16:31
An alternative and perhaps simpler solution is to implement this:

LocationHasItem(“[dungeon-L3-2F] Tower of Hera - Entrance”, ItemType.BigKey) || CanLightTorches(have)

to both the Big Chest and Compass Chests

**Comment by KatDevsGames** [comment] 2016-10-16 16:40
The issue there is it's a bit of an only-here solution rather than 
something that would work (and improve randomization) in every dungeon.

**Comment by ChristosOwen** [comment] 2016-11-04 02:34
This had been addressed and will be working correctly in v7.

**Closed as completed by ChristosOwen** 2016-11-04 02:34 UTC
Labels: bug
